![QuantConnect Logo](https://cdn.quantconnect.com/web/i/icon.png)
<hr>

In [ ]:
# tutorial: https://www.quantconnect.com/docs/v2/research-environment/datasets/equity-fundamental-data

qb = QuantBook()
symbols = [
    qb.add_equity(ticker, Resolution.DAILY).symbol
    for ticker in [
        "AAL",   # American Airlines Group, Inc.
        "ALGT",  # Allegiant Travel Company
        "ALK",   # Alaska Air Group, Inc.
        "DAL",   # Delta Air Lines, Inc.
        "LUV",   # Southwest Airlines Company
        "SKYW",  # SkyWest, Inc.
        "UAL"    # United Air Lines
    ]
]

# DataFrame of fundamental data
# is 10 the lookback here?
single_fundamental_df = qb.history(Fundamental, symbols[0], 10, flatten=True)
single_fundamental_df_nonflat = qb.history(Fundamental, symbols[0], 10, flatten=False)
# what does the flatten argument do? I dont see a difference between it and the non flattened version
# set_fundamental_df = qb.history(Fundamental, symbols, 10, flatten=True)
# all_fundamental_df = qb.history(Fundamental, qb.securities.keys(), 10, flatten=True)
# all_fundamentals_df = qb.history(Fundamentals, 10, flatten=True)

# # Fundamental objects
# single_fundamental_history = qb.history[Fundamental](symbols[0], 10)
# set_fundamental_history = qb.history[Fundamental](symbols, 10)
# all_fundamental_history = qb.history[Fundamental](qb.securities.keys(), 10)

# # Fundamentals objects
# all_fundamentals_history = qb.history[Fundamentals](qb.securities.keys(), 10)

In [15]:
single_fundamental_df_nonflat.head(2)

                   adjustedprice  \
symbol time
AAL    2026-06-24          16.14
       2026-06-25          17.44

                                                 assetclassification  \
symbol time
AAL    2026-06-24  QuantConnect.Data.Fundamental.AssetClassification
       2026-06-25  QuantConnect.Data.Fundamental.AssetClassification

                                                 companyprofile  \
symbol time
AAL    2026-06-24  QuantConnect.Data.Fundamental.CompanyProfile
       2026-06-25  QuantConnect.Data.Fundamental.CompanyProfile

                                                 companyreference  \
symbol time
AAL    2026-06-24  QuantConnect.Data.Fundamental.CompanyReference
       2026-06-25  QuantConnect.Data.Fundamental.CompanyReference

                   dollarvolume                                earningratios  \
symbol time
AAL    2026-06-24  2.672517e+09  QuantConnect.Data.Fundamental.EarningRatios
       2026-06-25  3.593875e+09  QuantConnect.Data.Fundamental.EarningRatios

                                                 earningreports  \
symbol time
AAL    2026-06-24  QuantConnect.Data.Fundamental.EarningReports
       2026-06-25  QuantConnect.Data.Fundamental.EarningReports

                                                 financialstatements  \
symbol time
AAL    2026-06-24  QuantConnect.Data.Fundamental.FinancialStatements
       2026-06-25  QuantConnect.Data.Fundamental.FinancialStatements

                   hasfundamentaldata market   marketcap  \
symbol time
AAL    2026-06-24                True    usa  9689292257
       2026-06-25                True    usa  9689292257

                                                 operationratios  pricefactor  \
symbol time
AAL    2026-06-24  QuantConnect.Data.Fundamental.OperationRatios          1.0
       2026-06-25  QuantConnect.Data.Fundamental.OperationRatios          1.0

                   pricescalefactor  \
symbol time
AAL    2026-06-24               1.0
       2026-06-25               1.0

                                                 securityreference  \
symbol time
AAL    2026-06-24  QuantConnect.Data.Fundamental.SecurityReference
       2026-06-25  QuantConnect.Data.Fundamental.SecurityReference

                   splitfactor                                valuationratios  \
symbol time
AAL    2026-06-24          1.0  QuantConnect.Data.Fundamental.ValuationRatios
       2026-06-25          1.0  QuantConnect.Data.Fundamental.ValuationRatios

                   value     volume
symbol time
AAL    2026-06-24  16.14  165583470
       2026-06-25  17.44  206070842

In [ ]:
single_fundamental_df.head(2)

                   adjustedprice  \
symbol time
AAL    2026-06-24          16.14
       2026-06-25          17.44

                                                 assetclassification  \
symbol time
AAL    2026-06-24  QuantConnect.Data.Fundamental.AssetClassification
       2026-06-25  QuantConnect.Data.Fundamental.AssetClassification

                                                 companyprofile  \
symbol time
AAL    2026-06-24  QuantConnect.Data.Fundamental.CompanyProfile
       2026-06-25  QuantConnect.Data.Fundamental.CompanyProfile

                                                 companyreference  \
symbol time
AAL    2026-06-24  QuantConnect.Data.Fundamental.CompanyReference
       2026-06-25  QuantConnect.Data.Fundamental.CompanyReference

                   dollarvolume                                earningratios  \
symbol time
AAL    2026-06-24  2.672517e+09  QuantConnect.Data.Fundamental.EarningRatios
       2026-06-25  3.593875e+09  QuantConnect.Data.Fundamental.EarningRatios

                                                 earningreports  \
symbol time
AAL    2026-06-24  QuantConnect.Data.Fundamental.EarningReports
       2026-06-25  QuantConnect.Data.Fundamental.EarningReports

                                                 financialstatements  \
symbol time
AAL    2026-06-24  QuantConnect.Data.Fundamental.FinancialStatements
       2026-06-25  QuantConnect.Data.Fundamental.FinancialStatements

                   hasfundamentaldata market   marketcap  \
symbol time
AAL    2026-06-24                True    usa  9689292257
       2026-06-25                True    usa  9689292257

                                                 operationratios  pricefactor  \
symbol time
AAL    2026-06-24  QuantConnect.Data.Fundamental.OperationRatios          1.0
       2026-06-25  QuantConnect.Data.Fundamental.OperationRatios          1.0

                   pricescalefactor  \
symbol time
AAL    2026-06-24               1.0
       2026-06-25               1.0

                                                 securityreference  \
symbol time
AAL    2026-06-24  QuantConnect.Data.Fundamental.SecurityReference
       2026-06-25  QuantConnect.Data.Fundamental.SecurityReference

                   splitfactor                                valuationratios  \
symbol time
AAL    2026-06-24          1.0  QuantConnect.Data.Fundamental.ValuationRatios
       2026-06-25          1.0  QuantConnect.Data.Fundamental.ValuationRatios

                   value     volume
symbol time
AAL    2026-06-24  16.14  165583470
       2026-06-25  17.44  206070842

In [ ]:
single_fundamental_df.iloc[0].valuationratios.pe_ratio

47.225806

In [10]:
vrs = single_fundamental_df.iloc[0].valuationratios

In [ ]:
vrs.